### PR TITLE
reduce test stage dependency with ReferenceTests

### PR DESCRIPTION
**Pull request by johnnychen94**
As @mgautam98 is going to improve this package with `AbstractArray{<:Colorant}` support ( #13 ) , I'm doing some preparation work now. This one is for the test, and I'll open a PR for CI later.

I'm still resistant to the usage of VisualRegressionTests for two reasons:

* Even if it's a test-only dependency, `VisualRegressionTests` is still very large a dependency with `Plots` and `Gtk`.
* The reference file can be very fragile because the output depends on how backends (Gtk) draw the figure. The failure in https://travis-ci.org/github/JuliaImages/ImageInpainting.jl/builds/647806320 is one such case. On the other hand, ReferenceTests only depends on image IO backend, which is quite faithful and reliable.

@juliohm Are you okay with this change?

### CODE REVIEW

**Comment by juliohm** [comment]
Thank you Jonny for suggesting ReferenceTests.jl again. I'll check the PR
tomorrow morning but I agree that visual regression tested is too complex
and unreliable.

**Comment by johnnychen94** [comment]
It doesn't look good to me that the behavior is platform dependent. I'll investigate how it happens later ~~today~~ tomorrow.

**Comment by juliohm** [comment]
Please go ahead and merge. The only missing feature of VisualRegressionTests.jl that I find really useful is the GUI that pops up when tests fail. It makes it easy to quickly update test data. However, I agree that the updates occur too often due to other noises related to GTK, etc.

**Comment by johnnychen94** [comment]
> The only missing feature of VisualRegressionTests.jl that I find really useful is the GUI that pops up when tests fail.

Yes, currently it displays images using ImageInTerminal, which sometimes doesn't give a clear view. There's a pending PR in ReferenceTests that renders images using ImageShow: https://github.com/JuliaTesting/ReferenceTests.jl/pull/41.

That PR is pending because some mock tests are needed to detect any possible regressions. I plan to update that PR this month and then I believe you'd be satisfied.

**Comment by juliohm** [comment]
Oh that is really nice. In that case I will try to get rid of VisualRegressionTests.jl in other packages as well in the future.

**Comment by juliohm** [comment]
Did you finish this PR @johnnychen94 ? Please feel free to merge if it is ready. That should indeed help the other PRs being written.

**Comment by johnnychen94** [comment]
Not yet, the CI error is concerning and I'm not sure what's the cause here. It would be great if you can have a look at it since you're more familiar with the algorithm.

I'm updating ReferenceTests these days to make it more stable.

**Comment by juliohm** [comment]
Of course, thank you for the heads up. Will try to take a look during the day.

**Comment by juliohm** [comment]
Is it my impression or the `Gray.(out)` is lowering the resolution of the image?

image

image

I think it is just the image size when I plot with `heatmap(out)` versus visualize the real size with `Gray.(out)` in Juno, but just wanted to confirm. Apparently the results are making sense on this branch, but for some reason the tests with the Gray images are failing. Should we just save the `*.txt` of the images instead of converting back to `Gray`?

**Comment by juliohm** [comment]
image

Also, is this information relevant? Should we set the number of CPU cores to 1 to get reproducible reference tests?

**Comment by johnnychen94** [comment]
I'm not sure if this is the same case; I just ran into a similar case that reference tests are broken when `ColorVectorSpace` is imported; part of the reason is the codes are not written generically to handle `Array{<:Number}` and `Array{Gray}` consistently.

I'm not 100% sure that ReferenceTests is working correctly, though.

Will try to fix it when I get some more time.

**Comment by juliohm** [comment]
@johnnychen94 did you succeed in the ReferenceTests.jl side?

**Comment by johnnychen94** [comment]
Not yet.

Unfortunately, I was quite busy this summer to continue this because of a series of day-to-day seminars. There're some unidentified bugs about its faithfully and my very limited time was spent on [adding more test cases](https://github.com/JuliaTesting/ReferenceTests.jl/pull/61)

If you have any plans on this package, please do it, I can just rebase on whatever you've done when I finally get here.

**Comment by juliohm** [comment]
Solved in #22

**Pull request closed without merging**
