### PR TITLE
Replace VisualRegressionTests by ReferenceTests

### PR DESCRIPTION
**Pull request by johnnychen94**
@tlnagy Cont. #6 

@juliohm The image results are changed, and it doesn't look good. Can you help fix it?

### CODE REVIEW

**Comment by juliohm** [comment]
Thank you @johnnychen94 , I will try to take a look tonight after  work. Could you please confirm this PR deprecates #6 ?

**Comment by johnnychen94** [comment]
yes this PR continues it to try to fix the test failure.

**Comment by johnnychen94** [comment]
It's wierd here that test passes if I do the following:

```julia
(v1.2) pkg> activate .
Activating environment at `~/Documents/Julia/ImageInpainting.jl/Project.toml`

julia> include("test/runtests.jl")
```

```julia
(v1.2) pkg> test ImageInpainting
```

and fails if I do

```julia
(v1.2) pkg> activate .
Activating environment at `~/Documents/Julia/ImageInpainting.jl/Project.toml`

(ImageInpainting) pkg> test
```

I guess it's related to multi-core behavior? No idea at all.

**Comment by juliohm** [comment]
@johnnychen94 I get the following error locally, probably the same error you get:

```julia
┌ Warning: test fails because PSNR -9.490427471076698 < 25
└ @ ReferenceTests ~/.julia/packages/ReferenceTests/0gZA4/src/equality_metrics.jl:31
Test for "Blobs.png" failed.
- REFERENCE -------------------
eltype: Gray{Float64}
size: (254, 256)
thumbnail:
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
-------------------------------
- ACTUAL ----------------------
eltype: Gray{Float64}
size: (254, 256)
thumbnail:
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
-------------------------------
Plain arrays: Error During Test at /home/juliohm/.julia/dev/ImageInpainting/test/runtests.jl:21
  Got exception outside of a @test
  You need to run the tests interactively with 'include("test/runtests.jl")' to update reference images
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] _test_reference(::typeof(ReferenceTests.default_image_equality), ::ReferenceTests.BeforeAfterImage, ::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{Gray{Float64},2}) at /home/juliohm/.julia/packages/ReferenceTests/0gZA4/src/core.jl:112
   [3] #test_reference#9 at /home/juliohm/.julia/packages/ReferenceTests/0gZA4/src/handlers.jl:21 [inlined]
   [4] test_reference(::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{Gray{Float64},2}) at /home/juliohm/.julia/packages/ReferenceTests/0gZA4/src/handlers.jl:21
   [5] #test_reference#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(ReferenceTests.test_reference), ::String, ::Array{Gray{Float64},2}) at /home/juliohm/.julia/packages/ReferenceTests/0gZA4/src/test_reference.jl:87
   [6] test_reference(::String, ::Array{Gray{Float64},2}) at /home/juliohm/.julia/packages/ReferenceTests/0gZA4/src/test_reference.jl:87
   [7] top-level scope at /home/juliohm/.julia/dev/ImageInpainting/test/runtests.jl:22
   [8] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [9] top-level scope at /home/juliohm/.julia/dev/ImageInpainting/test/runtests.jl:22
   [10] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [11] top-level scope at /home/juliohm/.julia/dev/ImageInpainting/test/runtests.jl:21
   [12] include at ./boot.jl:328 [inlined]
   [13] include_relative(::Module, ::String) at ./loading.jl:1094
   [14] include(::Module, ::String) at ./Base.jl:31
   [15] include(::String) at ./client.jl:431
   [16] top-level scope at none:5
   [17] eval(::Module, ::Any) at ./boot.jl:330
   [18] exec_options(::Base.JLOptions) at ./client.jl:271
   [19] _start() at ./client.jl:464
  
Test Summary:      | Error  Total
ImageInpainting.jl |     1      1
  Plain arrays     |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/juliohm/.julia/dev/ImageInpainting/test/runtests.jl:20
ERROR: Package ImageInpainting errored during testing
```

Can we split this PR into two separate PRs, one about updating the project to use Project.toml and another about moving from VisualRegressionTests.jl to ReferenceTests.jl? I am not 100% sure about the need for the latter though.

Regarding the error, I had similar errors with VisualRegressionTests.jl in the past: running the same tests twice and getting an error. It has to do with the version of ImageMagick.jl that is used in the tests I guess? Let's discuss this in a separate PR. Should we close this PR in favor of #6 ? It is more self contained.

**Comment by juliohm** [comment]
I will close this PR @johnnychen94 , we need to fix other things before changing the test suite, see #8

**Comment by johnnychen94** [comment]
I strongly believe that errors are not due to `ReferenceTests.jl` with my experiences with it. Changing the test suite minimizes the influence introduced by external changes (e.g, `GR`, `Plots`)

**Pull request closed without merging**
