### PR TITLE
Use ReferenceTests.jl

### LINKED ISSUE #21: Tests are hanging due to Gtk.jl
@johnnychen94 could you please try to run the tests locally? I am experiencing this issue where the following lines are causing the build to hang:

```julia
if !istravis
  Pkg.add("Gtk")
  using Gtk
end
```

The Gtk.jl is used locally by VisualRegressionTests.jl to compare the before and after of the inpainting operation. Did you have a chance to revisit #14 to replace VisualRegressionTests.jl with ReferenceTests.jl?

### PR DESCRIPTION
**Pull request by juliohm**
Fixes #21 

ReferenceTests.jl is a much cleaner approach compared to VisualRegressionTests.jl 👍🏽

### CODE REVIEW

**Comment by juliohm** [comment]
After this PR is merged, I will create a new one to migrate to GitHub Actions.

**Comment by juliohm** [comment]
I wonder if we can also run the tests in the other platforms? Currently I am only running the reference tests on Linux via the `visualtests` variable defined in runtests.jl Does ReferenceTests.jl handle different image formats in different platforms?

**Review by johnnychen94 — APPROVED** [review]
Sorry for the delay. I noticed that you have deleted some tests for color images, which was a failure in #14 (I'm not sure if it's an ImageInpainting or ReferenceTests issue). Since this package never does a serious test on color images, it's okay to keep it as it is. However, as a package under JuliaImages, it's expected that `ImageInpainting` should work with different color images seamlessly, so improvements are needed, which, of course, can be placed in future PRs.

> Does ReferenceTests.jl handle different image formats in different platforms?

Images are loaded via image IO backends, so it's expected to have the same result if they have the same backend installed. For example, if and only if `ImageMagick` is used.

**Comment by juliohm** [comment]
> Sorry for the delay. I noticed that you have deleted some tests for color images, which was a failure in #14 (I'm not sure if it's an ImageInpainting or ReferenceTests issue)

This package never supported color types. There is an open issue #13 for anyone interested in adding the functionality. I don't have the time at the moment, but I'd be happy to review a future PR.

I will merge this one as it solves the VisualRegressionTests.jl issue 👍🏽

**Pull request merged**
